config/routes.rb
Rails.application.routes.draw do
  # mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'articles#index'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new article_params
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Tu artículo ha sido publicado.' }
        format.json { render :show, status: :created, locations: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Tu artículo ha sido publicado.' }
        format.json { render :show, status: :created, locations: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Tu artículo ha sido eliminado' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <%= form_with(model: article, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :title, "Título" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Contenido:" %>
    <%= f.cktext_area :body, class: 'form-control' %>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= f.submit 'Publicar', class: 'btn btn-platzi-blue' %>
  </div>
  <% end %>
</div>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<div class="row">
  <div class="col-12">
    <div class="jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <h1 class="article-header">Editar artículo</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <%= render 'form', article: @article %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-12">
    <div class="jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <h1 class="article-header">Todos los artículos</h1>
          </div>
          <% if user_signed_in? %>
            <div class="col-12 text-right mt-auto">
              <%= link_to '<i class="fas fa-plus"></i> Artículo'.html_safe, new_article_path, class: 'btn btn-platzi-blue' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <% @articles.each do |article| %>
        <div class="card">
          <div class="card-body">
            <h2 class="anton"><%= link_to article.title, article %></h2>
            <hr>
            <div class="rawbody"><%= (raw article.body) %></div>
          </div>
        </div>
        <br>
      <% end %>
    </div>
  </div>
</div>
<script>
  $('.rawbody > p').not(':first-child, :nth-child(2)').hide();
  $('.rawbody > ol').hide();
  $('.rawbody > ul').hide();
</script>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-12">
    <div class="jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <h1 class="article-header">Nuevo artículo</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <%= render 'form', article: @article %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-12">
    <div class="jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <h1 class="article-header"><%= @article.title %></h1>
            <p class="author">Por <%= @article.user.name %></p>
            <div class="col mt-auto px-0">
              <%= link_to '↩ Volver', articles_path %>
            </div>
          </div>
          <% if user_signed_in? %>
            <div class="col-12 text-right mt-auto">
              <%= link_to '<i class="fas fa-pencil-alt"></i>'.html_safe, edit_article_path(@article) %>
              <%= link_to @article, method: :delete, data: { confirm: '¿Estás seguro de que quieres eliminar este artículo?' } do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="contianer">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <p>
        <%= (raw @article.body) %>
      </p>
    </div>
  </div>
</div>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Platziblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <!--
    <p class="notice"><%#= notice</p> %>
    <p class="alert"><%#= alert %></p>
    -->
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <%# link_to image_tag("logo_mini.png", class: 'navbar-brand img-fluid'), root_path %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to 'Inicio', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Posts', articles_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <p class="nav-link">|</p>
      </li>
      <% if user_signed_in? %>
        <div class="navbar-user-email">
          <%= current_user.email %>
        </div>
        <li class="nav-item">
          <%= link_to('Cerrar sesión', destroy_user_session_path, class: 'btn btn-platzi', method: :delete) %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Inicia sesión', user_session_path, class: 'btn btn-platzi' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>